GET http://localhost:3001/api/persons
###
GET http://localhost:3001/api/persons/635275811aa365bee8cdf1f4
###
DELETE http://localhost:3001/api/persons/635275811aa365bee8cdf1f4
###
PUT http://localhost:3001/api/persons/635275811aa365bee8cdf1f4
content-type: application/json

{
    "name": "Tamas",
    "number": "4444-555-6666"
}
###
POST http://localhost:3001/api/persons
content-type: application/json

{
    "name": "Tamas",
    "number": "1111-222-3333"
}
