GET http://localhost:3001/api/persons
###
GET http://localhost:3001/api/persons/635161985f7a6bd7b06dc244
###
DELETE http://localhost:3001/api/persons/2
###
POST http://localhost:3001/api/persons
content-type: application/json

{
    "name": "Norbert",
    "number": "1122-345-6789"
}
